# Generated by Django 4.1.7 on 2024-10-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_dept', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_phone', models.CharField(max_length=20)),
                ('employee_dob', models.DateField()),
                ('employee_doj', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=8)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('spouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_dob', models.DateField(blank=True, null=True)),
                ('spouse_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('spouse_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishWave.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('child_dob', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishWave.employees')),
            ],
        ),
    ]
