# Generated by Django 4.1.7 on 2024-10-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0004_employees_spouse_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
