# Generated by Django 4.1.7 on 2024-10-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0006_employees_address_employees_anniversary_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=255)),
                ('name_of_vendor', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('town_village', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=10)),
                ('gps_location_link', models.URLField(blank=True, null=True)),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(max_length=20)),
                ('manager_email', models.EmailField(max_length=255, unique=True)),
                ('store_general_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('headoffice_address', models.CharField(blank=True, max_length=255, null=True)),
                ('headoffice_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('headoffice_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('headoffice_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('headoffice_contact_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('headoffice_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('headoffice_contact_person_email', models.EmailField(max_length=255, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_no', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_branch', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('bank_account_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
