# Generated by Django 4.1.7 on 2024-10-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0007_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('img_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('company_id', models.IntegerField()),
            ],
        ),
    ]
