# Generated by Django 4.1.7 on 2024-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0008_templateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTemplateConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('template_img_id', models.IntegerField()),
                ('logo_name', models.CharField(max_length=255)),
                ('logo_path', models.CharField(max_length=255)),
                ('logo_size', models.CharField(max_length=50)),
                ('logo_x', models.FloatField()),
                ('logo_y', models.FloatField()),
                ('content', models.TextField()),
                ('content_x', models.FloatField()),
                ('content_y', models.FloatField()),
                ('employname_x', models.FloatField()),
                ('employname_y', models.FloatField()),
                ('text_colourcode', models.CharField(max_length=7)),
                ('text_size', models.IntegerField()),
                ('text_font', models.CharField(max_length=100)),
            ],
        ),
    ]
