# Generated by Django 4.1.7 on 2024-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0009_companytemplateconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsTable',
            fields=[
                ('ops_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('img_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_generate', models.BooleanField(default=False)),
                ('mail_send', models.BooleanField(default=False)),
                ('whats_app_send', models.BooleanField(default=False)),
                ('gift_sent', models.BooleanField(default=False)),
                ('cake_send', models.BooleanField(default=False)),
            ],
        ),
    ]
