# Generated by Django 4.1.7 on 2024-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishWave', '0010_opstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytemplateconfig',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytemplateconfig',
            name='logo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytemplateconfig',
            name='logo_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companytemplateconfig',
            name='logo_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companytemplateconfig',
            name='logo_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
